---
- name: Enable APT repositories
  apt_repository: repo='{{ item.repo }}' state=present
  with_items: COLLECTD_REPOS
  when: COLLECTD_REPOS
  tags:
         - collectd_addrepo

- name: Install DEB packages
  apt: name={{ item.package }} state=latest update_cache=yes
  with_items: COLLECTD_PACKAGES
  when: COLLECTD_PACKAGES
  tags:
         - collectd_install

